apiVersion: v1
kind: Service
metadata:
  name: ecommerce-backend-service
  namespace: 2401077
spec:
  type: NodePort
  selector:
    app: ecommerce-backend
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30077
