apiVersion: v1
kind: Service
metadata:
  name: ecommerce-frontend-service
  namespace: 2401077
spec:
  type: NodePort
  selector:
    app: ecommerce-frontend
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30078
